### ISSUE TITLE
Fix port detection to work with raw snippet

### ISSUE THREAD

**Issue by ViliamKopecky** [shakyShane/browser-sync#394]
Proxy doesn't work well in some cases. Lets imagine we have a simple webserver running on port `8080` and we include the same snippet as the proxy includes by default:

```
<script type='text/javascript' id="__bs_script__">//<![CDATA[
document.write("<script async src='/browser-sync/browser-sync-client.1.9.0.js'><\/script>".replace(/HOST/g, location.hostname).replace(/PORT/g, location.port));
//]]></script>
```

This fails:

1) because the replaces of `HOST` and `PORT` strings doesnt do nothing here.
2) if it would, it would fail also, because BS runs on `3000` and `location.port` is `8080`.

So lets replace `location.port` for `3000` hardcoded and fix the replacements:

```
<script type='text/javascript' id="__bs_script__">//<![CDATA[
document.write("<script async src='//HOST:PORT/browser-sync/browser-sync-client.1.9.0.js'><\/script>".replace(/HOST/g, location.hostname).replace(/PORT/g, location.port));
//]]></script>
```

Yeah, we load the `browser-sync-client.js` but BS doesn't work, because the script also uses `location.port` which is still `8080`.

So the wise thing would be, to have ability to define the port on which BS is running.

- Simply stating `data-bs-port="3000"`
- Parsing the src URL of the `<script src="//localhost:3000/...">`
- Setting some global variable (let's not do this one)

For this to work it would probably need to modify the `https://github.com/shakyShane/browser-sync/blob/master/lib/public/socket.io.js`. Am I right?

**Comment by shakyShane** [comment]
In proxy mode, the snippet is served by the same server as the proxy. This makes sense since if you're able to view the url provided by the proxy, then `/browser-sync/browser-sync-client.x.js` would be just fine.

You can run BrowserSync in `snippet` mode - which will give you a different snippet to use and will work with your server.

Just start BrowserSync without either the server or proxy options and you'll see what I mean. 

command line

```bash
browser-sync start
```

api

```
require("browser-sync")();
```
